Train:
  epochs: 100
  learning_rate: 0.01
  train_batch: 128
  val_batch: 1024

Model:
  name: Linear
  module: models.fc

Loss:
  loss: MSE      # BCE, BCEWithLogits or MSE
  output: Probs  # "Logits" or "Probs"

Data:
  reg_season: False
  post_season: True
  Agg:
    active: True
    data_cols: [Seed]